CLAN_TAG = ' GQQQY9'

API_URL = 'https://api.clashroyale.com/v1'

API_TOKEN = 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjEzMjRjNTQ5LTA5OTMtNDdjOC04MjU4LTRiYTRhMWUwYjk0OCIsImlhdCI6MTUzMjc1MzEyNiwic3ViIjoiZGV2ZWxvcGVyL2VhNDQyNGQ3LTkwMDQtNTUwOS04Y2FkLTMyNjJmYjI4NzhmMCIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyIxMDMuMjU1LjIyNy4xNzkiXSwidHlwZSI6ImNsaWVudCJ9XX0.MIBkuB8aF0BUjry-ExKldMEDdGcCv1j6rhABPNIyDQjffpKPdMHuXpCwsreAzV__XKoIvCB9_1NKK-mfG3j0hQ'

HEADERS = {
    'authorization': API_TOKEN,
    'Accept': 'application/json'
}

TRUSTED = ['#2YGJ8U0Q', '#YPY0LGVU', '#2P8UQY2YP', '#2RRRCUVC', '#202JJ9PPJ', '#P0RLVUYU', '#2LCCJQJLY', '#UR9GV2CR',
           '#RQUVJ2JL', '#YCL9UJR', '#20UUL8GCQ', '#VYQPL82Y', '#92G8YPRV', '#20RYP2GQP', '#8VUL0LLR9', '#9UQQCV8Q',
           '#22UPPC29U', '#YLVQUQYJ', '#PRPJCCQ9']
